### ISSUE TITLE
Quick Start Guide

### ISSUE THREAD

**Issue by PRabahy** [S-Hodgson-MMOARgames/Evolv.io-Unity#4]
How do I get this up and running on my machine? I've never used Unity before, but I am very familiar with Visual Studio and C#.

I'm guessing I'm not the only one that could benefit from some sort of quick start guide.

**Comment by S-Hodgson-MMOARgames** [comment]
There's lots of information on the web for working inside of Unity. 

The setup is pretty simple, and should work from within the editor by simply pressing play.

I went ahead and created a [getting started page.(https://github.com/S-Hodgson-MMOARgames/Evolv.io-Unity/blob/master/GettingStarted.md).
